trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'Azure subscription 1'

stages:

# ---------------- INIT + PLAN ----------------
- stage: Plan
  displayName: Terraform Init & Plan
  jobs:
  - job: TerraformPlan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    # 🔐 Azure login FIX (IMPORTANT)
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          terraform init
          terraform plan -out=tfplan

    - publish: tfplan
      artifact: tfplan


# ---------------- APPLY (Manual Approval) ----------------
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan
  condition: succeeded()

  jobs:
  - deployment: ApplyJob
    environment: 'prod-approval'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                terraform init
                terraform apply -auto-approve tfplan


# ---------------- DESTROY (Manual Approval) ----------------
- stage: Destroy
  displayName: Terraform Destroy
  dependsOn: Apply

  jobs:
  - deployment: DestroyJob
    environment: 'destroy-approval'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                terraform init
                terraform destroy -auto-approve
